// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuygi-1D0dW0kqmtdflJK7yc2qK19DXOw',
    appId: '1:995774207312:web:452ed6f9202923a4064855',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    authDomain: 'task-reminder-e4bdd.firebaseapp.com',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    measurementId: 'G-Q5NNXZ6K0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlIL_I7-Yf-g59Hh7DjY7H689l3VzSRg',
    appId: '1:995774207312:android:8d2142138e8b55c7064855',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv335fcstUTDWdRuJ-mVPQomJyhqFAjWo',
    appId: '1:995774207312:ios:b899d33ab864e82b064855',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    iosBundleId: 'com.example.taskReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv335fcstUTDWdRuJ-mVPQomJyhqFAjWo',
    appId: '1:995774207312:ios:b899d33ab864e82b064855',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    iosBundleId: 'com.example.taskReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuygi-1D0dW0kqmtdflJK7yc2qK19DXOw',
    appId: '1:995774207312:web:f21f2cff75c01dc5064855',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    authDomain: 'task-reminder-e4bdd.firebaseapp.com',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    measurementId: 'G-S67ZPXBGN9',
  );
}
