// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyAFlIL_I7-Yf-g59Hh7DjY7H689l3VzSRg',
    appId: '1:995774207312:web:your_web_app_id_here',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    authDomain: 'task-reminder-e4bdd.firebaseapp.com',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: 'AIzaSyAFlIL_I7-Yf-g59Hh7DjY7H689l3VzSRg',
    appId: '1:995774207312:android:8d2142138e8b55c7064855',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: 'AIzaSyAFlIL_I7-Yf-g59Hh7DjY7H689l3VzSRg',
    appId: '1:995774207312:ios:your_ios_app_id_here',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    iosBundleId: 'com.example.taskReminder',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: 'AIzaSyAFlIL_I7-Yf-g59Hh7DjY7H689l3VzSRg',
    appId: '1:995774207312:ios:your_macos_app_id_here',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    iosBundleId: 'com.example.taskReminder',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: 'AIzaSyAFlIL_I7-Yf-g59Hh7DjY7H689l3VzSRg',
    appId: '1:995774207312:web:your_windows_app_id_here',
    messagingSenderId: '995774207312',
    projectId: 'task-reminder-e4bdd',
    authDomain: 'task-reminder-e4bdd.firebaseapp.com',
    storageBucket: 'task-reminder-e4bdd.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
